"""empty message

Revision ID: 6d38ca393b09
Revises: 
Create Date: 2026-03-24 15:26:03.257041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d38ca393b09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('taxadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('demandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_sei', sa.String(length=100), nullable=False),
    sa.Column('quantidade_masp', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('acao_id', sa.Integer(), nullable=False),
    sa.Column('entrada_ccpt', sa.Date(), nullable=False),
    sa.Column('quantidade_taxados', sa.Integer(), nullable=True),
    sa.Column('taxador_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acao_id'], ['acoes.id'], ),
    sa.ForeignKeyConstraint(['taxador_id'], ['taxadores.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demandas')
    op.drop_table('unidades')
    op.drop_table('taxadores')
    op.drop_table('acoes')
    # ### end Alembic commands ###
